services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard

    ports:
      - "${VPN_IP}:53:53/tcp"
      - "${VPN_IP}:53:53/udp"

    volumes:
      - ${ADGUARD_WORK}:/opt/adguardhome/work
      - ${ADGUARD_CONF}:/opt/adguardhome/conf

    networks:
      - pub_net

networks:
  pub_net:
    external: true
