services: # starting service block

  home_assistant: # service name
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home_assistant

    networks:
      - pub_net

    ports:
      - "${VPN_IP}:8123:8123"

    environment:
      - PUID=${HA_UID}
      - PGID=${HA_GID}
      - TZ=${HA_TZ}

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HA_CONFIG_PATH}:/config
      - /run/dbus:/run/dbus:ro
      - /dev:/dev

    healthcheck: # defining health check block
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8123 || exit 1"] # command being run
      interval: 1h # interval of test
      timeout: 10s # 10s of no response
      retries: 3 # retry 3 times
      start_period: 40s # allow 40s for starting

    cap_add:
      - NET_ADMIN
      - NET_RAW

networks:
  pub_net:
    external: true
